name: Create Release Candidate

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Specify the type of release'
        required: true
        type: choice
        default: 'minor'
        options:
          - 'minor'
          - 'major'

jobs:
  create_release_candidate_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggered from main branch
        run: |
          if [ "${{ github.ref }}" != 'refs/heads/main' ]; then
            echo "This workflow is allowed to run only from main branch."
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate release version
        id: calculate_versions
        run: |
          GRADLE_VERSION=$(grep '^pluginVersion=' gradle.properties | cut -d'=' -f2)
          CURRENT_UNRELEASED_VERSION=${GRADLE_VERSION%-SNAPSHOT}
          echo "Gradle base version: ${CURRENT_UNRELEASED_VERSION}"

          # Determine the new release version based on the release type
          if [ "${{ github.event.inputs.release_type }}" == "major" ]; then
            IFS='.' read -r -a version_parts <<< "$CURRENT_UNRELEASED_VERSION"
            major=${version_parts[0]}
            NEW_MAJOR_VERSION=$((major + 1)).0.0
            NEW_RELEASE_VERSION="${NEW_MAJOR_VERSION}"
          else
            NEW_RELEASE_VERSION="${CURRENT_UNRELEASED_VERSION}"
          fi
          
          echo "release_version=${NEW_RELEASE_VERSION}"
          echo "release_version=${NEW_RELEASE_VERSION}" >> $GITHUB_ENV
          
          RELEASE_CANDIDATE_VERSION="${NEW_RELEASE_VERSION}-RC.0"
          echo "New release candidate version: ${RELEASE_CANDIDATE_VERSION}"
          echo "release_candidate_version=${RELEASE_CANDIDATE_VERSION}" >> $GITHUB_ENV

      - name: Update version
        run: |
          sed -i "s/^pluginVersion=.*/pluginVersion=${{ env.release_candidate_version }}/" gradle.properties
          cat gradle.properties

      - name: Create release candidate branch and commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout -b jetbrains/release-candidate/${{ env.release_version }}
          git add gradle.properties
          git commit -m "Prepares jetbrains plugin release candidate version for ${{ env.release_version }}"
          git push --set-upstream origin jetbrains/release-candidate/${{ env.release_version }}
