name: Public release

on:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.calculate_versions.outputs.release_version }}
      new_unreleased_version: ${{ steps.calculate_versions.outputs.new_unreleased_version }}
    steps:
      - name: Check if triggered from RC branch
        run: |
          if [[ ! "${{ github.ref }}" =~ ^refs/heads/jetbrains/release-candidate/.*$ ]]; then
            echo "This workflow is allowed to run only from RC branches matching 'jetbrains/release-candidate/**'."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate release version
        id: calculate_versions
        run: |
          GRADLE_VERSION=$(grep '^pluginVersion=' gradle.properties | cut -d'=' -f2)
          CURRENT_UNRELEASED_VERSION=${GRADLE_VERSION%-RC.*}
          echo "Current unreleased version: ${CURRENT_UNRELEASED_VERSION}"

          # Calculate new unreleased version (release version + minor increment)
          IFS='.' read -r -a version_parts <<< "$CURRENT_UNRELEASED_VERSION"
          minor=${version_parts[1]}
          NEW_UNRELEASED_VERSION="${version_parts[0]}.$((minor + 1)).0"

          echo "release_version=${CURRENT_UNRELEASED_VERSION}"
          echo "release_version=${CURRENT_UNRELEASED_VERSION}" >> $GITHUB_OUTPUT
          
          echo "new_unreleased_version=${NEW_UNRELEASED_VERSION}"
          echo "new_unreleased_version=${NEW_UNRELEASED_VERSION}" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: '${{ secrets.WORKFLOW_TOKEN }}'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Create release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b jetbrains/release/${{ needs.prepare.outputs.release_version }}

      - name: Update version and patch changelog
        run: |
          sed -i "s/^pluginVersion=.*/pluginVersion=${{ needs.prepare.outputs.release_version }}/" gradle.properties
          cat gradle.properties

      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          RELEASE_CHANNELS: nightly,default
        run: ./gradlew publishPlugin

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle.properties
          git add CHANGELOG.md
          git commit -m "Release jetbrains plugin version ${NEW_RELEASE_VERSION}"
          git push --set-upstream origin jetbrains/release/${{ needs.prepare.outputs.release_version }}
          git tag jb-${{ needs.prepare.outputs.release_version }}
          git push origin --tags

      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew getChangelog --console=plain -q --no-header --no-summary > release-notes.md

          gh release create jb-${{ needs.prepare.outputs.release_version }} \
            --title jb-${{ needs.prepare.outputs.release_version }} \
            --verify-tag \
            --notes-file release-notes.md

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload jb-${{ needs.prepare.outputs.release_version }} ./build/distributions/*


      - name: Prepare PR to main branch after release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          BRANCH=after-jb-release-${{ needs.prepare.outputs.release_version }}
          
          git checkout -b $BRANCH
          
          NEW_VERSION=${{ needs.prepare.outputs.new_unreleased_version }}-SNAPSHOT
          sed -i "s/^pluginVersion=.*/pluginVersion=${NEW_VERSION}/" gradle.properties
          cat gradle.properties
          
          git add gradle.properties
          git commit -m "Prepare for next development iteration"
          git push --set-upstream origin $BRANCH
          
          gh pr create \
            --title "Release jetbrains plugin version ${NEW_RELEASE_VERSION}" \
            --body "Release jetbrains plugin version ${NEW_RELEASE_VERSION}" \
